import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.login}>
        <a href="/login">Login</a>
      </div>

      <div className={styles.introduce}>
        <p>
          당신의 참신한 <p className={styles.accent_blue}>아이디어</p>.
          <br />
          까먹지 않게,
          <br />
          <p className={styles.accent_green}>빠르게</p> 등록하세요.
        </p>
      </div>
    </div>
  )
}

export default Home
